name: dart_utils
description: A compillation of utils by Diviloper for Diviloper

environment:
  sdk: '>=2.9.0-21.10.beta <3.0.0'

dependencies:
  equatable: ^1.2.3

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.3
